### ISSUE TITLE
Failed to parse an AXML (Instagram)

### ISSUE THREAD

**Issue by ghost** [Ayrx/axmldecoder#1]
I got an Instagram app from apk pure for testing: https://apkpure.com/instagram-android/com.instagram.android/variant/245.0.0.0.3-APK

axmldecoder failed with this error:
```
'assertion failed: `(left == right)`
 left: `Some("http://schemas.amazon.com/apk/res/android")`,
 right: `None`', github.com-1ecc6299db9ec823/axmldecoder-0.4.0/src/xml.rs:101:9
```

as you can see this line: https://github.com/Ayrx/axmldecoder/blob/master/src/xml.rs#L101

**Comment by Ayrx** [comment]
@grubeli Thanks for the report! Can you see if a70f72ab149246d35e4344e995e13b47ad028c22 fixes the issue for you? I've tested it but would be good to get confirmation.

**Comment by ghost** [comment]
works! thanks.
