### ISSUE TITLE
Namespace missing Error

### ISSUE THREAD

**Issue by ghost** [Ayrx/axmldecoder#3]
Error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Namespace missing: ', src/main.rs:59:39
stack backtrace:
```

File:
[Insta Followers.zip](https://github.com/Ayrx/axmldecoder/files/9154061/Insta.Followers.zip)

**Comment by ghost** [comment]
same error for this app
[base.zip](https://github.com/Ayrx/axmldecoder/files/9154100/base.zip)

**Comment by Ayrx** [comment]
https://github.com/Ayrx/axmldecoder/commit/be885fece620bbdc6847a593631c4e047b510b85 should fix this problem.

We just skip appending the namespace to the attribute if it's not found in a namespace chunk.
