### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by ghost** [Ayrx/axmldecoder#4]
Error:
```
'called `Option::unwrap()` on a `None` value'
```

File:
[Boost Wifi Lite.zip](https://github.com/Ayrx/axmldecoder/files/9154075/Boost.Wifi.Lite.zip)

**Comment by Ayrx** [comment]
I can't seem to replicate the error on this. Do you have more info on the commit ID / what you invoked to trigger this?

**Comment by ghost** [comment]
It was my mistake expecting that platformBuildVersionCode exists
