### ISSUE TITLE
axmldecoder::parse - Namespace missing: android

### ISSUE THREAD

**Issue by ghost** [Ayrx/axmldecoder#7]
`axmldecoder::parse` returns `Namespace missing: android` error

[manifest_missing_android.zip](https://github.com/Ayrx/axmldecoder/files/9173260/manifest_missing_android.zip)

**Comment by Ayrx** [comment]
be885fece620bbdc6847a593631c4e047b510b85 should fix this problem.

We just skip appending the namespace to the attribute if it's not found in a namespace chunk.
