### ISSUE TITLE
the crate fails to build because of a squashed dependency

### ISSUE THREAD

**Issue by marcograss** [Ayrx/axmldecoder#8]
The crate now fails to build because a dependency version was removed from crates.io

> error: failed to select a version for the requirement `funty = "~1.2"`
> candidate versions found which didn't match: 2.0.0, 1.1.0, 1.0.1, ...
> location searched: crates.io index
> required by package `bitvec v0.22.1`
>     ... which satisfies dependency `bitvec = "^0.22.1"` of package `deku v0.13.1`
>     ... which satisfies dependency `deku = "~0.13"` of package `axmldecoder v0.5.0

**Comment by Ayrx** [comment]
Thanks for the report, it looks like I need to spend some time and upgrade `bitvec` to v1.0.1.
